<!-- Page: Detail Keuangan -->
<div id="page-detail-keuangan" class="page-content hidden page-section">
    <!-- Header -->
    <div class="section-header">
        <div>
            <h3 class="section-title">Detail Keuangan</h3>
            <p class="text-secondary" style="font-size: 0.875rem; margin-top: 4px;">Rincian pendapatan berdasarkan master pembayaran per blok.</p>
        </div>
        <div class="header-actions" style="display: flex; gap: 12px; align-items: center; flex-wrap: wrap;">
            <div style="display: flex; gap: 8px; align-items: center;">
                <button class="button-secondary button-sm" style="padding: 10px; border-radius: 12px;" onclick="prevMonthDetail()" title="Bulan Sebelumnya"><i data-lucide="chevron-left" style="width: 16px; height: 16px;"></i></button>
                <select id="filter-bulan-detail" class="input-field select-custom" style="font-size: 0.875rem; padding: 10px; min-width: 120px; border-radius: 12px;" onchange="loadDetailKeuangan()">
                    <option value="all" selected>Semua Bulan</option>
                    <?php
                    $months = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];
                    foreach($months as $i => $m) {
                        echo "<option value='$i'>$m</option>";
                    }
                    ?>
                </select>
                <select id="filter-tahun-detail" class="input-field select-custom" style="font-size: 0.875rem; padding: 10px; min-width: 100px; border-radius: 12px;" onchange="loadDetailKeuangan()">
                    <option value="all" selected>Semua Tahun</option>
                    <?php
                    $currY = (int)date('Y');
                    for($y = $currY; $y >= $currY - 3; $y--) echo "<option value='$y'>$y</option>";
                    ?>
                </select>
                <button class="button-secondary button-sm" style="padding: 10px; border-radius: 12px;" onclick="nextMonthDetail()" title="Bulan Selanjutnya"><i data-lucide="chevron-right" style="width: 16px; height: 16px;"></i></button>
            </div>
            <button class="button-secondary button-sm" style="padding: 10px 16px; border-radius: 12px;" onclick="exportDetailKeuangan()"><i data-lucide="download" style="margin-right: 6px; width: 18px; height: 18px;"></i> Export</button>
        </div>
    </div>

    <!-- Summary Cards -->
    <div class="summary-wrapper" style="margin-bottom: 24px;">
        <div class="summary-card-modern glass-card" style="border-bottom: 4px solid #3b82f6;">
            <div class="summary-icon-wrapper bg-blue-light text-blue"><i data-lucide="users"></i></div>
            <p class="card-label m-0">Total Setoran Lunas</p>
            <h3 id="dk-total-lunas" class="card-value text-color m-0">0 Setoran</h3>
        </div>
        <div class="summary-card-modern glass-card" style="border-bottom: 4px solid #10b981;">
            <div class="summary-icon-wrapper bg-emerald-light text-emerald"><i data-lucide="banknote"></i></div>
            <p class="card-label m-0">Total Pendapatan</p>
            <h3 id="dk-total-pendapatan" class="card-value text-emerald m-0">Rp 0</h3>
        </div>
    </div>

    <!-- Main Table Container -->
    <div class="glass-card" style="padding: 0; overflow: hidden; border-radius: 20px;">
        <div style="padding: 20px 24px; border-bottom: 1px solid var(--border-color); display: flex; justify-content: space-between; align-items: center; background: rgba(255,255,255,0.02);">
            <h4 style="font-size: 1.1rem; margin: 0; font-weight: 700;">Rincian Komponen Iuran Per Blok</h4>
        </div>
        <div class="table-responsive" style="overflow-x: auto;">
            <table class="modern-table rekon-table" style="width: 100%; border-collapse: collapse; white-space: nowrap;">
                <thead id="dk-table-head" style="background: var(--secondary-bg);">
                    <!-- Headers generated by JS -->
                </thead>
                <tbody id="dk-table-body">
                    <!-- Rows generated by JS -->
                </tbody>
                <tfoot id="dk-table-foot" style="background: var(--secondary-bg); font-weight: bold;">
                    <!-- Footer generated by JS -->
                </tfoot>
            </table>
        </div>
        
        <!-- Pagination Controls -->
        <div id="dk-pagination" style="display: none; justify-content: space-between; align-items: center; padding: 16px 24px; border-top: 1px dashed var(--border-color); background: rgba(255,255,255,0.01);">
            <span id="dk-page-info" class="text-secondary" style="font-size: 0.8125rem;">Menampilkan 0 data</span>
            <div style="display: flex; gap: 8px;">
                <button class="button-secondary button-sm" style="padding: 8px 12px; border-radius: 8px;" onclick="prevDkPage()"><i data-lucide="chevron-left" style="width: 16px; height: 16px;"></i></button>
                <div id="dk-page-numbers" style="display: flex; gap: 4px;"></div>
                <button class="button-secondary button-sm" style="padding: 8px 12px; border-radius: 8px;" onclick="nextDkPage()"><i data-lucide="chevron-right" style="width: 16px; height: 16px;"></i></button>
            </div>
        </div>
    </div>
</div>