<!-- Page: Laporan Pembukuan (Trial Balance) -->
<div id="page-pembukuan" class="page-content hidden page-section">
    <!-- SaaS Style Summary Dashboard -->
    <div class="summary-3-grid mb-24">
        <div class="glass-card-deluxe stagger-item stagger-delay-1 card-top-accent">
            <div class="card-icon-deluxe icon-tone-success">
                <i data-lucide="trending-up"></i>
            </div>
            <p class="card-label">Total Debit (Masuk)</p>
            <h3 id="pb-debit" class="card-value text-emerald">Rp 0</h3>
            <div class="card-sub-info">Penerimaan iuran & dana</div>
        </div>
        
        <div class="glass-card-deluxe stagger-item stagger-delay-2 card-top-danger">
            <div class="card-icon-deluxe icon-tone-danger">
                <i data-lucide="trending-down"></i>
            </div>
            <p class="card-label">Total Kredit (Keluar)</p>
            <h3 id="pb-kredit" class="card-value text-red">Rp 0</h3>
            <div class="card-sub-info">Pengeluaran & alokasi pos</div>
        </div>

        <div class="glass-card-deluxe stagger-item stagger-delay-3 card-highlight-accent">
            <div class="card-icon-deluxe icon-tone-accent-shadow">
                <i data-lucide="wallet"></i>
            </div>
            <p class="card-label">Net Saldo Tersedia</p>
            <h3 id="pb-saldo" class="card-value text-color">Rp 0</h3>
            <div class="card-sub-info">Total dana kas RT pusat</div>
        </div>
    </div>

    <!-- Filter & Periode -->
    <div class="glass-card page-filter-card">
        <p class="text-secondary page-filter-desc">Neraca lajur (Trial Balance) perputaran kas RT.</p>
        <div class="header-actions page-filter-actions">
            <div class="page-filter-group">
                <button class="button-secondary button-sm compact-btn-icon" onclick="prevMonthPembukuan()"><i data-lucide="chevron-left" class="icon-14"></i></button>
                <select id="filter-bulan-pembukuan" class="input-field select-custom compact-control minw-120" onchange="loadPembukuan()"></select>
                <select id="filter-tahun-pembukuan" class="input-field select-custom compact-control minw-100" onchange="loadPembukuan()"></select>
                <button class="button-secondary button-sm compact-btn-icon" onclick="nextMonthPembukuan()"><i data-lucide="chevron-right" class="icon-14"></i></button>
            </div>
            <button class="button-secondary button-sm compact-btn" onclick="exportPembukuanCSV()"><i data-lucide="download" class="icon-16 icon-mr-6"></i> Export</button>
        </div>
    </div>

    <!-- Tab Navigasi -->
    <div class="sub-nav-container hide-on-print pb-subnav-shell">
        <button class="sub-nav-tab active" onclick="switchPbTab('pb-tab-ledger', this)">
            <i data-lucide="list"></i> Rincian Transaksi
        </button>
        <button class="sub-nav-tab" onclick="switchPbTab('pb-tab-laporan', this)">
            <i data-lucide="briefcase"></i> Laporan Pos Anggaran
        </button>
    </div>

    <!-- Tab 1: General Ledger (Rincian Transaksi Baris) -->
    <div id="pb-tab-ledger" class="pb-tab-content">
        <div class="glass-card hide-card-border-print table-panel mb-24">
            <div class="hide-on-print table-panel-head">
                <h4 class="table-panel-title inline-wrap-8"><i data-lucide="list" class="text-blue"></i> Rincian Transaksi (Buku Besar)</h4>
            </div>
            
        <div class="table-responsive table-scroll-shell">
            <table class="modern-table rekon-table w-full table-nowrap pb-ledger-table">
                <thead class="pb-ledger-head">
                    <tr>
                        <th class="pb-ledger-th pb-ledger-th-date">Tanggal</th>
                        <th class="pb-ledger-th">Keterangan & Ref</th>
                        <th class="pb-ledger-th">Pos Alokasi</th>
                        <th class="text-right pb-ledger-th pb-ledger-th-money">Debit (Masuk)</th>
                        <th class="text-right pb-ledger-th pb-ledger-th-money">Kredit (Keluar)</th>
                        <th class="text-right pb-ledger-th pb-ledger-th-balance">Saldo Berjalan</th>
                    </tr>
                </thead>
                <tbody id="pb-ledger-body">
                    <!-- Rows generated by JS -->
                </tbody>
                <tfoot id="pb-ledger-foot" class="pb-ledger-foot">
                    <!-- Footer generated by JS -->
                </tfoot>
            </table>
        </div>
        <div id="pb-pagination" class="pagination-bar pb-pagination-shell">
            <span id="pb-page-info" class="text-secondary pagination-bar-info">Menampilkan 0 data</span>
            <div class="pagination-actions">
                <button class="button-secondary button-sm compact-btn" onclick="prevPbPage()"><i data-lucide="chevron-left" class="icon-16"></i></button>
                <div id="pb-page-numbers" class="row-gap-4"></div>
                <button class="button-secondary button-sm compact-btn" onclick="nextPbPage()"><i data-lucide="chevron-right" class="icon-16"></i></button>
            </div>
        </div>
        </div> <!-- Penutup glass-card -->
    </div> <!-- Penutup Tab 1 -->

    <!-- Tab 2: Laporan Kas Warga (Sisa Detail Pos) -->
    <div id="pb-tab-laporan" class="pb-tab-content hidden">
        <div class="glass-card hide-card-border-print pb-report-shell">
            
            <!-- Kop Surat / Judul Laporan -->
            <div class="pb-report-header">
                <div class="hide-on-print pb-report-icon-wrap">
                    <i data-lucide="briefcase" class="icon-32"></i>
                </div>
                <h2 class="pb-report-title">Laporan Pos Anggaran</h2>
                <p class="text-secondary pb-report-subtitle">Rincian mutasi dan sisa dana pada masing-masing pos anggaran / kas</p>
                <p class="text-color font-bold pb-report-period" id="laporan-periode-text">Periode: Semua Bulan</p>
            </div>
            
            <div id="laporan-pos-cards" class="pb-report-cards-grid">
                <!-- Cards generated by JS -->
            </div>

            <div class="pb-report-total-card">
                <div>
                    <p class="pb-report-total-label">Total Sisa Kas Pos Anggaran</p>
                    <h2 id="laporan-total-sisa" class="pb-report-total-value">Rp 0</h2>
                </div>
                <button class="button-primary hide-on-print rounded-12" onclick="window.print()"><i data-lucide="printer" class="icon-18 icon-mr-8"></i> Cetak PDF Laporan</button>
            </div>

            <!-- History Transaksi di Bawah Laporan -->
            <div class="pb-history-section">
                <h4 class="pb-history-title">Riwayat Transaksi Periode Ini</h4>
                <div class="table-responsive pb-history-table-wrap">
                    <table class="modern-table pb-history-table">
                        <thead class="pb-history-head">
                            <tr>
                                <th class="pb-history-th">Tanggal</th>
                                <th class="pb-history-th">Pos Anggaran</th>
                                <th class="pb-history-th">Keterangan</th>
                                <th class="pb-history-th text-right">Nominal Mutasi</th>
                            </tr>
                        </thead>
                        <tbody id="laporan-pos-history-body">
                            <!-- Diisi oleh JS -->
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

<style>
.pb-subnav-shell {
    margin-bottom: 24px;
    border-bottom: 1px solid var(--border-color);
}

.pb-ledger-table {
    border-collapse: collapse;
}

.pb-ledger-head {
    background: var(--secondary-bg);
}

.pb-ledger-th {
    padding: 16px 24px;
}

.pb-ledger-th-date {
    width: 120px;
}

.pb-ledger-th-money {
    width: 130px;
}

.pb-ledger-th-balance {
    width: 140px;
    color: var(--text-color);
}

.pb-ledger-foot {
    background: var(--secondary-bg);
    color: var(--text-color);
    font-weight: bold;
}

.pb-pagination-shell {
    padding: 16px 24px;
    background: rgba(255, 255, 255, 0.01);
    margin-top: 0;
}

.pb-report-shell {
    padding: 32px;
    border-radius: 20px;
    margin-bottom: 24px;
    background: var(--secondary-bg);
}

.pb-report-header {
    text-align: center;
    margin-bottom: 32px;
}

.pb-report-icon-wrap {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 64px;
    height: 64px;
    background: color-mix(in srgb, var(--accent-color) 10%, transparent);
    color: var(--accent-color);
    border-radius: 20px;
    margin-bottom: 16px;
}

.pb-report-title {
    margin: 0 0 8px 0;
    font-size: 1.8rem;
    font-weight: 800;
    color: var(--text-color);
}

.pb-report-subtitle {
    margin: 0;
    font-size: 0.95rem;
}

.pb-report-period {
    margin: 8px 0 0 0;
    font-size: 1rem;
}

.pb-report-cards-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
    gap: 16px;
    margin-bottom: 32px;
}

.pb-report-total-card {
    padding: 24px;
    border-radius: 16px;
    background: linear-gradient(
        135deg,
        color-mix(in srgb, var(--accent-color) 10%, transparent),
        transparent
    );
    border: 1px solid var(--accent-color);
    display: flex;
    justify-content: space-between;
    align-items: center;
    flex-wrap: wrap;
    gap: 16px;
}

.pb-report-total-label {
    margin: 0 0 4px 0;
    color: var(--text-secondary-color);
    font-weight: 600;
    text-transform: uppercase;
    font-size: 0.8rem;
}

.pb-report-total-value {
    margin: 0;
    font-size: 2rem;
    font-weight: 800;
    color: var(--text-color);
}

.pb-history-section {
    margin-top: 40px;
    padding-top: 32px;
    border-top: 2px dashed var(--border-color);
}

.pb-history-title {
    font-size: 1.2rem;
    margin: 0 0 16px 0;
    font-weight: 800;
    color: var(--text-color);
}

.pb-history-table-wrap {
    border-radius: 16px;
    border: 1px solid var(--border-color);
    overflow: hidden;
}

.pb-history-table {
    width: 100%;
    border-collapse: collapse;
    text-align: left;
    font-size: 0.85rem;
}

.pb-history-head {
    background: var(--secondary-bg);
    border-bottom: 2px solid var(--border-color);
}

.pb-history-th {
    padding: 12px 20px;
}

/* Gaya Spesifik Ketika Pengguna Mencetak ke PDF / Kertas */
@media print {
    body { background: #fff !important; color: #000 !important; }
    #sidebar, #main-header, .header-actions, .hide-on-print, .grid-container, .section-header { display: none !important; }
    #main-content { margin-left: 0 !important; padding: 0 !important; }
    .hide-card-border-print { border: none !important; box-shadow: none !important; background: transparent !important; padding: 0 !important; margin: 0 !important;}
    .text-color, .text-secondary { color: #000 !important; }
    /* Paksa grid tetap berbentuk kotak saat di-print */
    #laporan-pos-cards { grid-template-columns: repeat(2, 1fr) !important; gap: 16px !important; }
    .pos-laporan-card { border: 1px solid #ccc !important; background: #fff !important; page-break-inside: avoid; }
    .text-emerald { color: #059669 !important; }
    .text-red { color: #dc2626 !important; }
}
</style>
</div>