<!-- Modular JS (split by function, load order matters) -->
<script src="<?= htmlspecialchars(smart_asset('public/js/core.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/file-source-picker.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/dashboard.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/workspace.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/warga.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/ruang-warga.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/global-warga.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/keuangan.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/agenda.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/gallery.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/laporan-iuran.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/rekonsiliasi.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/keuangan-global.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/detail-keuangan.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/pos-keuangan.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/pembukuan.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/keamanan.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>
<script src="<?= htmlspecialchars(smart_asset('public/js/info.js', 'auto'), ENT_QUOTES, 'UTF-8') ?>"></script>